<?php

declare(strict_types=1);

return [
    'table' => 'materials',
    'data' => [
        [
            'name' => 'Aluminum Sheet 6061',
            'slug' => 'aluminum-sheet-6061',
            'sku' => 'AL-6061-001',
            'description' => 'High-quality aluminum sheet, 6061 grade',
            'category' => 'Metals',
            'unit' => 'sqft',
            'unit_price' => 15.50,
            'stock_quantity' => 500.00,
            'min_order_quantity' => 1.00,
            'supplier' => 'Metal Supply Co.',
            'is_active' => true,
        ],
        [
            'name' => 'Stainless Steel 304',
            'slug' => 'stainless-steel-304',
            'sku' => 'SS-304-001',
            'description' => 'Corrosion-resistant stainless steel 304',
            'category' => 'Metals',
            'unit' => 'lb',
            'unit_price' => 3.25,
            'stock_quantity' => 1000.00,
            'min_order_quantity' => 5.00,
            'supplier' => 'Steel Distributors Inc.',
            'is_active' => true,
        ],
        [
            'name' => 'PLA Filament',
            'slug' => 'pla-filament',
            'sku' => '3DP-PLA-001',
            'description' => '1.75mm PLA filament for 3D printing',
            'category' => '3D Printing',
            'unit' => 'kg',
            'unit_price' => 20.00,
            'stock_quantity' => 50.00,
            'min_order_quantity' => 1.00,
            'supplier' => '3D Materials Plus',
            'is_active' => true,
        ],
        [
            'name' => 'ABS Plastic Sheet',
            'slug' => 'abs-plastic-sheet',
            'sku' => 'PL-ABS-001',
            'description' => 'High-impact ABS plastic sheet',
            'category' => 'Plastics',
            'unit' => 'sqft',
            'unit_price' => 8.75,
            'stock_quantity' => 200.00,
            'min_order_quantity' => 1.00,
            'supplier' => 'Plastics Warehouse',
            'is_active' => true,
        ],
        [
            'name' => 'Carbon Steel Round Bar',
            'slug' => 'carbon-steel-round-bar',
            'sku' => 'CS-RB-001',
            'description' => 'Cold-rolled carbon steel round bar',
            'category' => 'Metals',
            'unit' => 'ft',
            'unit_price' => 5.50,
            'stock_quantity' => 300.00,
            'min_order_quantity' => 1.00,
            'supplier' => 'Industrial Steel Supply',
            'is_active' => true,
        ],
    ],
];
