<?php

declare(strict_types=1);

return [
    'table' => 'site_settings',
    'data' => [
        [
            'setting_key' => 'site_name',
            'setting_value' => 'Manufacturing Services',
            'setting_type' => 'string',
            'group_name' => 'general',
            'description' => 'Website name',
            'is_public' => true,
            'display_order' => 1,
        ],
        [
            'setting_key' => 'site_tagline',
            'setting_value' => 'Quality Manufacturing Solutions',
            'setting_type' => 'string',
            'group_name' => 'general',
            'description' => 'Website tagline',
            'is_public' => true,
            'display_order' => 2,
        ],
        [
            'setting_key' => 'contact_email',
            'setting_value' => 'contact@example.com',
            'setting_type' => 'string',
            'group_name' => 'contact',
            'description' => 'Primary contact email',
            'is_public' => true,
            'display_order' => 3,
        ],
        [
            'setting_key' => 'contact_phone',
            'setting_value' => '+1 (555) 123-4567',
            'setting_type' => 'string',
            'group_name' => 'contact',
            'description' => 'Primary contact phone',
            'is_public' => true,
            'display_order' => 4,
        ],
        [
            'setting_key' => 'business_hours',
            'setting_value' => 'Monday - Friday: 8:00 AM - 6:00 PM',
            'setting_type' => 'string',
            'group_name' => 'contact',
            'description' => 'Business operating hours',
            'is_public' => true,
            'display_order' => 5,
        ],
        [
            'setting_key' => 'currency',
            'setting_value' => 'USD',
            'setting_type' => 'string',
            'group_name' => 'pricing',
            'description' => 'Default currency',
            'is_public' => true,
            'display_order' => 6,
        ],
        [
            'setting_key' => 'tax_rate',
            'setting_value' => '8.5',
            'setting_type' => 'number',
            'group_name' => 'pricing',
            'description' => 'Default tax rate percentage',
            'is_public' => false,
            'display_order' => 7,
        ],
        [
            'setting_key' => 'estimate_validity_days',
            'setting_value' => '30',
            'setting_type' => 'number',
            'group_name' => 'pricing',
            'description' => 'Number of days estimates are valid',
            'is_public' => false,
            'display_order' => 8,
        ],
        [
            'setting_key' => 'maintenance_mode',
            'setting_value' => 'false',
            'setting_type' => 'boolean',
            'group_name' => 'system',
            'description' => 'Enable maintenance mode',
            'is_public' => false,
            'display_order' => 9,
        ],
        [
            'setting_key' => 'items_per_page',
            'setting_value' => '20',
            'setting_type' => 'number',
            'group_name' => 'system',
            'description' => 'Default pagination limit',
            'is_public' => false,
            'display_order' => 10,
        ],
    ],
];
